'use client';

// import type { Metadata } from "next";
import { Provider } from 'react-redux';
import { store } from './store/store';
import './styles/globals.scss';

// export const metadata: Metadata = {
//   title: "Niloware",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          {children}
        </Provider>
      </body>
    </html>
  );
}
